set nocompatible
filetype off

" Vundle
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" Indentation related
set tabstop=4
set expandtab " Expand tab to spaces
set shiftwidth=4
set softtabstop=4
set autoindent

" View related
"set cursorline " Highlight cursor line set showmatch " Match brackets
syntax on

" Search related
set incsearch " Incremental search
set hlsearch " Highlight search
set ignorecase
set smartcase " Ignore ignorecase when uppercase characters are present

" Navigation related
set scrolloff=3 " Minimum number of lines to show below/above the cursor

" Shortcuts
set pastetoggle=<F2>


" Persistent undo
set undofile
set undolevels=1000
set undoreload=1000

" Fold baby fold
set foldmethod=indent   "fold based on indent
set foldnestmax=10      "deepest fold is 10 levels
set nofoldenable        "dont fold by default
set foldlevel=1         "this is just what i use

""" Plugins 
" Python autocomplete
Bundle 'davidhalter/jedi-vim'

" Modified lines since last commit in gutter
Bundle 'airblade/vim-gitgutter'

" Ctrl-P to browse files
Bundle 'kien/ctrlp.vim'

" Syntax checking for vim
Bundle "scrooloose/syntastic"

" Faster jumping around
Bundle "Lokaltog/vim-easymotion"
let g:EasyMotion_leader_key = '<Leader>'

" vim-tmux-navigator
Bundle "christoomey/vim-tmux-navigator"

filetype plugin indent on
