if has("python3")
    command! -nargs=1 Py py3 <args>
else
    command! -nargs=1 Py py <args>
endif

set nocompatible
set bs=2
filetype off

" Vundle
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" Indentation related
set tabstop=4
set expandtab " Expand tab to spaces
set shiftwidth=4
set softtabstop=4
set autoindent

au FileType html setl sw=2 sts=2 ts=2 et
au FileType htmldjango setl sw=2 sts=2 ts=2 et
au FileType javascript setl sw=2 sts=2 ts=2 et
au BufNewFile,BufRead *.py set textwidth=99
highlight BadWhitespace ctermbg=red guibg=darkred
au BufRead,BufNewFile *.py,*.pyw,*.c,*.h match BadWhitespace /\s\+$/


" View related
"set cursorline " Highlight cursor line set showmatch " Match brackets
syntax on

" Search related
set incsearch " Incremental search
set hlsearch " Highlight search
set ignorecase
set smartcase " Ignore ignorecase when uppercase characters are present

" Navigation related
set scrolloff=3 " Minimum number of lines to show below/above the cursor

" Shortcuts
set pastetoggle=<F2>

" Persistent undo
set undofile
set undolevels=1000
set undoreload=1000

" Fold baby fold
set foldmethod=indent   "fold based on indent
set foldnestmax=10      "deepest fold is 10 levels
set nofoldenable        "dont fold by default
set foldlevel=1         "this is just what i use

""" Plugins 
" Python autocomplete
Bundle 'Valloric/YouCompleteMe'
Bundle 'davidhalter/jedi-vim'
"let g:ycm_path_to_python_interpreter = '/usr/bin/python3'
let g:ycm_filetype_specific_completion_to_disable = { 'python' : 1 }

Bundle 'scrooloose/nerdtree'

" Modified lines since last commit in gutter
Bundle 'airblade/vim-gitgutter'

" Ctrl-P to browse files
Bundle 'ctrlpvim/ctrlp.vim'

" Syntax checking for vim
Bundle "scrooloose/syntastic"

" Faster jumping around
Bundle "Lokaltog/vim-easymotion"
let g:EasyMotion_leader_key = '<Leader>'

" vim-tmux-navigator
Bundle "christoomey/vim-tmux-navigator"

Bundle "groenewege/vim-less"

Bundle "Xuyuanp/nerdtree-git-plugin"

Bundle "mxw/vim-jsx"

Bundle "tpope/vim-fugitive"

Bundle 'powerline/powerline', {'rtp': 'powerline/bindings/vim/'}
set t_Co=256 " Powerline doesn't show colours on my terminal without this
set laststatus=2 " Powerline doesn't show up without this for me
set noshowmode

call vundle#end()
filetype plugin indent on
"nnoremap ,m :w <BAR> !lessc % > %:p:r.css<CR><space>
au BufNewFile,BufRead *.less set filetype=less

autocmd FileType nerdtree setlocal nocursorcolumn

let g:ctrlp_user_command = ['.git/', 'cd %s && git ls-files . -co --exclude-standard']

nnoremap <leader>jd :YcmCompleter GoTo<CR>

let g:syntastic_python_checkers=['pyflakes']

nmap <leader>ne :NERDTreeToggle<cr>
