# Rehash completion index to pick up new commands automatically
zstyle ":completion:*:commands" rehash 1

# Source .zshrc in all shells at USR2 signal
trap "source ~/.zshrc && rehash" USR2

HISTFILE="$HOME/.zsh_history"
HISTSIZE=500000
SAVEHIST=500000
setopt inc_append_history # append into history file
setopt share_history
setopt extended_history       # record timestamp of command in HISTFILE
bindkey \^U backward-kill-line

source $HOME/dotfiles/dotfiles/zshrc.d/functions.sh
source /usr/bin/virtualenvwrapper.sh
source ~/.zsh_plugins.sh
ls $HOME/.localzshrc >/dev/null 2>/dev/null && source $HOME/.localzshrc

export LESS=-R
export LESS_TERMCAP_mb=$'\E[1;31m'     # begin blink
export LESS_TERMCAP_md=$'\E[1;36m'     # begin bold
export LESS_TERMCAP_me=$'\E[0m'        # reset bold/blink
export LESS_TERMCAP_so=$'\E[01;44;33m' # begin reverse video
export LESS_TERMCAP_se=$'\E[0m'        # reset reverse video
export LESS_TERMCAP_us=$'\E[1;32m'     # begin underline
export LESS_TERMCAP_ue=$'\E[0m'        # reset underline

export EDITOR="nvim"
export PYTHONSTARTUP=$HOME/.pythonrc.py
export FZF_DEFAULT_COMMAND='fd --type file --follow --hidden --exclude .git'
export FZF_DEFAULT_OPTS='--color hl:underline:reverse,hl+:underline:reverse'
export GOPATH="/home/gagan/projects/go-src/"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

export ZSH="$(antibody home)/https-COLON--SLASH--SLASH-github.com-SLASH-robbyrussell-SLASH-oh-my-zsh"
export WORDCHARS='_-'

export PATH="/usr/local/bin/:$PATH:/usr/local/go/bin:$HOME/projects/go-src/bin/:$HOME/.yarn/bin/:$(ruby -e 'puts Gem.user_dir')/bin:$HOME/.poetry/bin:$HOME/.cargo/bin/"
export DISABLE_UPDATE_PROMPT=true
export GTK_USE_PORTAL=1  # Make Firefox use KDE file dialog

alias diff='diff --color=auto'
alias grep='grep --color=auto'
alias ip='ip -color=auto'
alias ls='ls --color=auto'
alias grep="grep --color=auto"
alias bc="bc -l"
alias vps="ssh -t gaganpreet.in 'su -'"
alias pie="perl -p -i -e"
alias rsync="rsync -aP"
alias antibodybundle="antibody bundle < ~/dotfiles/dotfiles/zsh_plugins.txt > ~/.zsh_plugins.sh"
alias rez="pkill -usr2 zsh"
alias gcal="gcalcli --calendar 'Gaganpreet Arora'  quick"

## Some conditional aliases
better_alias ba better_alias
ba cat bat
ba ls exa
ba top ytop
ba vim nvim


eval "$(starship init zsh)"
eval $(keychain --eval --agents ssh id_rsa)
eval "$(direnv hook zsh)"
eval "$(ntfy shell-integration)"

fortune

fpath=($HOME/dotfiles/dotfiles/zshrc.d/fpath $fpath)
autoload -Uz compinit && compinit -i


export PATH="$HOME/.poetry/bin:$PATH"
