# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="afowler"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(django git github pip python vundle virtualenvwrapper)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...
function alarm()
{
    sleep $1 && mplayer $HOME/alarm.mp3 -loop 0
}

function sum()
{
    awk 'BEGIN {sum=0}
              {sum += $0}
         END {print(sum)}'
}

function avg()
{
    awk 'BEGIN {sum=0; count=0}
              {sum += $0; count += 1}
         END {print(sum/count)}'
}

# Git ignore generate
function gi()
{
    curl http://gitignore.io/api/$@;
}

# Check mv if it's being done in a git directory
function check_mv()
{
    git status > /dev/null 2>&1
    if (( ! $? ))
    then
        echo "You're in a git directory, did you mean to use git mv?"
        return
    fi
    mv $@
}
alias mv="check_mv"
alias amv="mv"

alias grep="grep --color=auto"
alias bc="bc -l"
alias vps="ssh -t gaganpreet.in 'su -'"
alias pie="perl -p -i -e"
alias rsync="rsync -aP"
alias imfl="./configure && make && make install" # I'm feeling lucky

# Some useful python utils
# I found a nice list here: http://ominian.com/2011/02/27/python-batteries-included/
alias pyserv="python -m SimpleHTTPServer 8001"
alias jsont="python -m json.tool"

# Switch to 3g when internet is down
alias wanswitch='ssh root@192.168.1.1 "sh /tmp/switch.sh"'

## Some conditional aliases
# Better df: http://projects.gw-computing.net/projects/dfc/repository
type dfc > /dev/null && alias df="dfc"
# Better grep: http://betterthangrep.com/install/
type ack > /dev/null && alias grep="ack" && alias agrep="/bin/grep --color=auto"
type htop > /dev/null && alias top="htop"
type colordiff > /dev/null && alias diff="colordiff -W 300"

# Bind alt+y to cd -
bindkey -s '\ey' "cd -\n"
# Bind alt+r to ls -trl
bindkey -s '\er' "ls -trl\n"

# If wildcard doesn't expand, pass it on to the command
setopt no_nomatch

export EDITOR="vim"
export PYTHONSTARTUP=$HOME/.pythonrc.py
export PATH=$HOME/firefox:$PATH

source /usr/bin/virtualenvwrapper.sh

# Rehash completion index to pick up new commands automatically
zstyle ":completion:*:commands" rehash 1

# Source .zshrc in all shells at USR2 signal
trap "source ~/.zshrc && rehash" USR2
alias rez="pkill -usr2 zsh"

fortune
