function alarm()
{
    sleep $1 && mplayer $HOME/alarm.mp3 -loop 0
}

function sum()
{
    awk 'BEGIN {sum=0}
              {sum += $0}
         END {print(sum)}'
}

function avg()
{
    awk 'BEGIN {sum=0; count=0}
              {sum += $0; count += 1}
         END {print(sum/count)}'
}

function is_image_corrupt()
{
    identify -regard-warnings -verbose $1 > /dev/null 2>&1
    echo $?
}

export LESS=-R
export LESS_TERMCAP_mb=$'\E[1;31m'     # begin blink
export LESS_TERMCAP_md=$'\E[1;36m'     # begin bold
export LESS_TERMCAP_me=$'\E[0m'        # reset bold/blink
export LESS_TERMCAP_so=$'\E[01;44;33m' # begin reverse video
export LESS_TERMCAP_se=$'\E[0m'        # reset reverse video
export LESS_TERMCAP_us=$'\E[1;32m'     # begin underline
export LESS_TERMCAP_ue=$'\E[0m'        # reset underline

alias diff='diff --color=auto'
alias grep='grep --color=auto'
alias ip='ip -color=auto'
alias ls='ls --color=auto'
alias grep="grep --color=auto"
alias bc="bc -l"
alias vps="ssh -t gaganpreet.in 'su -'"
alias pie="perl -p -i -e"
alias rsync="rsync -aP"

export EDITOR="nvim"
export PYTHONSTARTUP=$HOME/.pythonrc.py
export FZF_DEFAULT_COMMAND='fd --type file --follow --hidden --exclude .git'
export GOPATH="/home/gagan/projects/go-src/"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export PATH="/usr/local/bin/:$PATH:/usr/local/go/bin:$HOME/.yarn/bin/"
source /usr/bin/virtualenvwrapper.sh
ls $HOME/.localzshrc >/dev/null 2>/dev/null && source $HOME/.localzshrc

# Rehash completion index to pick up new commands automatically
zstyle ":completion:*:commands" rehash 1

# Source .zshrc in all shells at USR2 signal
trap "source ~/.zshrc && rehash" USR2
alias rez="pkill -usr2 zsh"


HISTFILE="$HOME/.zsh_history"
HISTSIZE=500000
SAVEHIST=500000
setopt INC_APPEND_HISTORY # append into history file
setopt extended_history       # record timestamp of command in HISTFILE

fortune

alias antibodybundle="antibody bundle < ~/dotfiles/dotfiles/zsh_plugins.txt > ~/.zsh_plugins.sh"
export ZSH="$(antibody home)/https-COLON--SLASH--SLASH-github.com-SLASH-robbyrussell-SLASH-oh-my-zsh"
eval "$(starship init zsh)"
source ~/.zsh_plugins.sh
eval $(keychain --eval --agents ssh id_rsa)

function better_alias {
    type $2 > /dev/null
    if (( $? != 0 ))
    then
        echo "$2 not installed, using default $1"
    else
        alias -g "$1"="$2"
    fi
}

## Some conditional aliases
better_alias ba better_alias
ba df dfc
ba cat bat
ba ls exa
ba du dust
ba top ytop
ba vim nvim
